### ISSUE TITLE
Keep getting unknown encoder

### ISSUE THREAD

**Issue by geekteq** [AlBundy33/hb_rb#2]
unknown video-encoder x264
unknown video-encoder x265
and so on.. regardless of them being installed or not (they are installed all of them but seems they can't be found)

Trying one of the default examples: hb.rb --input /dev/dvd --output "~/test/Output_#pos#.mkv"

x264 0.148.2705 3f5ed56
x265 [info]: HEVC encoder version 1.9
x265 [info]: build info [Linux][GCC 5.3.1][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX AVX2 FMA3 LZCNT BMI2

They all get "listed" when I run hb.rb with no additions so it seems to find it but not working later..

**Comment by geekteq** [comment]
I removed the check for the encoder in lib and then it worked.. so it's the lookup for the encoder that fails somehow..

**Comment by AlBundy33** [comment]
The encoders are part of HandBrake - so there is nothing to install. 

Can you show me the output of hb.rb with the available encoders? 

Have you tried an older version of HandBrake?

**Comment by geekteq** [comment]
Attached the output of hb.rb --help
No, have not tried an older version but removing the check seems to work (albeit not the best practice) ;) 
[hb.log.zip](https://github.com/AlBundy33/hb_rb/files/1204762/hb.log.zip)

**Comment by AlBundy33** [comment]
It seems that the output of HandBrakeCLI has changed becaus the available encoders and the default seems to be wrong. 
Maybe there are also other options that are not parsed correctly.

**Comment by AlBundy33** [comment]
I've tried HandbrakeCLI 1.0.7 (Windows) without any problems.
HandbrakeCLI --help shows

```
Video Options ----------------------------------------------------------------

   -e, --encoder <string>  Select video encoder:
                               x264
                               qsv_h264
                               x265
                               mpeg4
                               mpeg2
                               VP8
                               VP9
                               theora
       --encoder-preset <string>
                           Adjust video encoding settings for a particular
                           speed/efficiency tradeoff (encoder-specific)
```
with this output hb.rb --help shows this

`        --encoder ENCODER            sets the video-encoder to use (available: x264, qsv_h264, x265, mpeg4, mpeg2, VP8, VP9, theora)`

**Comment by geekteq** [comment]
Well.. 

Using, as it would seem, 1.0.4 from the Ubuntu PPA. And I also get from --help.

   -e, --encoder <string>  Set video library encoder
                            Options: x264/x265/mpeg4/mpeg2/VP8/theora
                            (default: mpeg4)

and hb.rb --help shows this
        --encoder ENCODER            sets the video-encoder to use (available: Options: x264/x265/mpeg4/mpeg2/VP8/theora, (default: mpeg4))

Which is the same when I uncomment the check for encoders.. but the issue is when I'm trying to actually run hb.rb with a target.. then it says 

unknown video-encoder {whatever encoder I select form above}

**Comment by AlBundy33** [comment]
That's ok because hb.rb parses the output of handbrakeCLI --help and expects the encoders one by one (one per line).
In older versions the encoders where displayed all in one line separated by "/".

Sowith older versions of HandbrakeCLI the list of available encoders is wrong (i think there is only one encoder in the list that is named like "Options: a/b/c/d (default: c)"

I'll check if I can support older versions too...

**Comment by AlBundy33** [comment]
Can you send me the complete output of HandbrakeCLI --help
For Windows I've found only 1.0.2 which is still correct. :-/

**Comment by geekteq** [comment]
Attached.
[hb.txt](https://github.com/AlBundy33/hb_rb/files/1211718/hb.txt)

**Comment by geekteq** [comment]
Sent the hb.rb output instead I think.. heres handbrakecli

[hbcli.txt](https://github.com/AlBundy33/hb_rb/files/1211804/hbcli.txt)

**Comment by AlBundy33** [comment]
I've found an older version and made some changes - so you can try the latest revision from github to check if it works for you now.

**Comment by AlBundy33** [comment]
Should be fixed...

**Comment by geekteq** [comment]
Confirmed. Thanks a lot. Let me know where to send beer 👍
